### ISSUE TITLE
Proofing menu glitches

### ISSUE THREAD

**Issue by MarcAnt01** [brullsker/FastNote#12]
![image](https://user-images.githubusercontent.com/43090263/51339366-8f187880-1a8c-11e9-86ed-5ca3cd62f15f.png)

I would suggest you to disable it, as Microsoft doesn't provide required APIs

**Comment by brullsker** [comment]
Hey, thanks for reporting this issue, and sorry for the late reply.
As far as I know, this is a system menu provided by Windows, so apart from turning off spellcheck altogether, there isn't much I can do to work around it.
Anyways, I'm gonna report this problem to Microsoft, as they are the ones responsible for fixing it.
I'm sorry that I can't help you with that particular issue.

**Comment by MarcAnt01** [comment]
> Hey, thanks for reporting this issue, and sorry for the late reply.
> As far as I know, this is a system menu provided by Windows, so apart from turning off spellcheck altogether, there isn't much I can do to work around it.
> Anyways, I'm gonna report this problem to Microsoft, as they are the ones responsible for fixing it.
> I'm sorry that I can't help you with that particular issue.

Yep, we had the same issue with Unigram, it's Microsoft being asshole and not providing the required API he uses in Microsoft Edge and other apps of his. At the end Unigram dev decided to disable spell check, I think it's a compromise, but still the best solution, I would suggest you to do the same for FastNote.

**Comment by brullsker** [comment]
I finally came around to work on the app again, and this issue seems to have been resolved with the Windows 10 November 2019 update.
